tools:
    external_code_coverage: true
filter:
    excluded_paths:
        - tests/*
checks:
    php:
        # set to 2 as $db is used by the MyBB
        no_short_variable_names:
            minimum: '2'
        # Have to be used in plugins for accessing the context
        no_global_keyword: false
        # eval() is used by the MyBB template engine
        no_eval: false
        # MyBB has some specific naming conventions
        naming_conventions:
            local_variable: '^[a-z][a-zA-Z0-9_]*$'
            abstract_class_name: ^Abstract|Factory$
            utility_class_name: 'Utils?$'
            constant_name: '^[A-Z][A-Z0-9]*(?:_[A-Z0-9]+)*$'
            property_name: '^[a-z][a-zA-Z0-9]*$'
            method_name: '^(?:[a-z]|__)[a-zA-Z0-9_]*$'
            parameter_name: '^[a-z][a-zA-Z0-9]*$'
            interface_name: '^[A-Z][a-zA-Z0-9]*Interface$'
            type_name: '^[A-Z][a-zA-Z0-9]*$'
            exception_name: '^[A-Z][a-zA-Z0-9]*Exception$'
            isser_method_name: '^(?:[a-z]|__)[a-zA-Z0-9_]*$'
        # most MyBB functions are not in camelCase
        function_in_camel_caps: false